# Generated by Django 5.1.4 on 2024-12-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название курса', max_length=50, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, help_text='Укажите описание курса', null=True, verbose_name='Описание курса')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='lms/preview/course', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название урока', max_length=50, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Укажите описание урока', null=True, verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='lms/preview/lesson', verbose_name='Превью')),
                ('video', models.CharField(blank=True, help_text='Укажите ссылку на видео', max_length=200, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
